# NumPy — LAB
Fill in every `# your code here`. Check-your-numbers are on the board.


In [1]:
import numpy as np


### 1.  Make an array
Create a NumPy array of these daily sales: 250, 800, 1200, 450, 999, 1500, 300, 2100. Call it `sales`.


In [2]:
# your code here
sales = np.array([250, 800, 1200, 450, 999, 1500, 300, 2100])

### 2.  Inspect
Print the array's `shape`, `size`, and `dtype`.


In [3]:
# your code here
print("Shape: ", sales.shape)
print("Size: ", sales.size)
print("dtype: ", sales.dtype)


Shape:  (8,)
Size:  8
dtype:  int64


### 3.  Generate
Use `np.arange` to make the even numbers from 0 to 20 (inclusive of 20 is fine or not — your call).


In [4]:
# your code here
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


### 4.  Slicing
From `sales`, print the **first 3** values, and the **last** value.


In [6]:
# your code here
print("First 3 values: ",sales[0:3])
print("Last Value: ", sales[-1])

First 3 values:  [ 250  800 1200]
Last Value:  2100


### 5.  Vectorize
Apply a 10% discount to every value in `sales` (multiply by 0.9). No loop.


In [7]:
# your code here
print(sales * 0.9)

[ 225.   720.  1080.   405.   899.1 1350.   270.  1890. ]


### 6.  Boolean mask
How many days had sales over **1000**? Then show **which** values they were.


In [12]:
# your code here
print("Number of days had sales over 1000: ", (sales > 1000).sum())

Number of days had sales over 1000:  3


### 7.  Two conditions
Show sales that were **between 500 and 1500** (greater than 500 AND less than 1500).


In [13]:
# your code here
sales[(sales>500) & (sales<1500)]

array([ 800, 1200,  999])

### 8.  np.where
Label each day `'target hit'` if sales > 1000, else `'below'`.


In [16]:
# your code here
print(np.where(sales > 1000, "target hit", "below"))

['below' 'below' 'target hit' 'below' 'below' 'target hit' 'below'
 'target hit']


### 9.  Reshape to 2D
Reshape `sales` (8 values) into a **2 x 4** grid. Call it `grid`.


In [26]:
# your code here
sales = sales.reshape(2,4)
sales

array([[ 250,  800, 1200,  450],
       [ 999, 1500,  300, 2100]])

### 10.  axis
On `grid`, compute the sum **down each column** (`axis=0`) and the sum **across each row** (`axis=1`).


In [19]:
# your code here
print("axis = 0 : ", sales.sum(axis = 0))
print("axis = 1 : ", sales.sum(axis = 1))

axis = 0 :  [1249 2300 1500 2550]
axis = 1 :  [2700 4899]


### 11.  Broadcasting
Add the bonus `[10, 20, 30, 40]` to **every row** of `grid`.


In [25]:
# your code here
bonus = [10,20,30, 40]
print("Sales : ", sales)
sales + bonus

Sales :  [[ 250  800 1200  450]
 [ 999 1500  300 2100]]


array([[ 260,  820, 1230,  490],
       [1009, 1520,  330, 2140]])

### Challenge — back to pandas
Make a DataFrame with a `sales` column from your array. Add a `tier` column using `np.where` that is `'big'` when sales > 1000 else `'small'`.


In [ ]:
# your code here
